config/routes.rb
Rails.application.routes.draw do

	get "/", to: "home#inicial"

	get "/cv", to: "cv#dados_pessoais"	
	get "/dados_pessoais", to: "cv#dados_pessoais"
	get "/educacao", to: "cv#educacao"
	get "/certificados", to: "cv#certificados"
	get "/idiomas", to: "cv#idiomas"
	get "/exp_prof", to: "cv#experienciaprof"
	get "/ativcompl", to: "cv#ativcompl"
	get "/informatica", to: "cv#informatica"

	get "/materias", to:"materias#materias"

	resources :materias do
		collection do
			delete :remover_por_nome
			get :adicionar_materia
			post :adicionar_materia
		end
		resources :provas do
			collection do
			
			end
		end

		resources :trabalhos do
			collection do
				
			end
		end

	end



	
end

app/models/materia.rb
class Materia
	include Mongoid::Document

  #fields
  field :nome,                   :type=>String,  :default=>nil
  field :creditos,     			 :type=>Integer, :default=>nil
  field :numero_de_provas,       :type=>Integer, :default=>'3'
  field :numero_de_trabalhos,	 :type=>Integer, :default=>'0'
  
  has_many :provas
  has_many :trabalhos
  

end

app/models/prova.rb
class Prova
	include Mongoid::Document

  #fields
  field :data,                   :type=>String,  :default=>nil
  field :nota,     				 :type=>Float,   :default=>nil
  field :peso,       			 :type=>Integer, :default=>'0'

  belongs_to :materia
  	
  

  

end

app/models/trabalho.rb
class Trabalho
	include Mongoid::Document

  #fields
  field :nome, 					 :type=>String,  :default=>nil
  field :data,                   :type=>String,  :default=>nil
  field :nota,     				 :type=>Float,   :default=>nil
  field :peso,       			 :type=>Integer, :default=>'0'

  belongs_to :materia
  	
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cv_controller.rb
class CvController < ApplicationController

  def dados_pessoais
  end

  def educacao
  end
  
  def certificados
  end

  def idiomas
  end

  def experienciaprof
  end  

  def ativcompl
  end  

  def informatica
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def inicial
  end

end

app/controllers/materias_controller.rb
class MateriasController < ApplicationController

  def index
  end

  def create
  	nova_materia = Materia.new
  	nova_materia.nome = params['nome']
  	nova_materia.creditos = params['creditos']
  	nova_materia.save!

  	redirect_to :back

  end

  def show 
  	@materia = Materia.all.find params['id']
  end



  def remover_por_nome
  	@nome_para_remover = params['nome']
  	@materia = Materia.where(:nome=>@nome_para_remover)
  	@materia.destroy
  	redirect_to :back
  	flash[:notice] = "#{@nome_para_remover} foi removido"
  end



 end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController

  def index
    @materia = Materia.find params['materia_id']
  end

  def create
    @materia = Materia.find params['materia_id']
    nova_prova = Prova.new
    nova_prova.materia_id = @materia.id
    nova_prova.peso = params['peso']
    nova_prova.nota = params['nota']
    nova_prova.data = params['data']
    nova_prova.save!

    redirect_to :back
  end

    

 end

app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController

  def index
    @materia = Materia.find params['materia_id']
  end

  def create
    @materia = Materia.find params['materia_id']
    novo_trabalho = Trabalho.new
    novo_trabalho.materia_id = @materia_id
    novo_trabalho.nome = params['nome']
    novo_trabalho.peso = params['peso']
    novo_trabalho.nota = params['nota']
    novo_trabalho.data = params['data']
    novo_trabalho.save!

    redirect_to :back
  end

  

    

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cv/ativcompl.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>

  <h1>Atividades Complementares</h1>

  <ul>
    <li>Projeto de Iniciação Científica
      <br>Tema: RTK positioning technique via RDS
      <br>Orientador: Prof. Renato Alves Borges
      <br>Instituição: Universidade de Brasília
      <br>
    </li>
      
      <br>
    
    <li>Monitoria de Laboratório de Eletromagnetismo II
      <br>Professor: Plínio Ricardo Ganime Alves
      <br>Instituição: Universidade de Brasília
      <br>
    </li>  
      
      <br>

    <li>Monitoria de Física II
      <br>Professor: Demétrio Antonio da Silva Filho
      <br>Instituição: Universidade de Brasília
      <br>
    </li>
  </ul>

</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/certificados.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>
  <h1>Bolsas e Certificados</h1>

    <ul>
    <li>Participação na <b>I Escola Internacional de Energia Solar 2015</b>
      <br>UnB, 28 horas 
      <br>
    </li>
      
      <br>
    
    <li>Bolsa para graduação sanduíche através do programa <b>Ciências sem Fronteiras/CAPES</b>
      <br>Vigência: 2014
      <br>
    </li>  
      
      <br>

    <li>Mini-cursos <b>Princípios de conversão CA/CC e Componente Principais de Sistema CC</b>
      <br>ONS, 14 horas
      <br>
    </li>
  </ul>
  <br>
  <br>
  <br>
  <br>
  
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/dados_pessoais.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>

  <h1>Dados Pessoais</h1>
  <br>
  <b>Data de Nascimento:</b> 08 Abril 1994
  <br>
  <b>Endereço:</b> QE 15 Conjunto B Casa 21, 71050-020, Guará, Brasília, Brasil
  <br>
  <b>Telefone:</b> <a href="tel:+5561974008158">+55 61 97400-8158</a>
  <br>
  <b>Email:</b> <a href="mailto:arthurcarvalhosantos@gmail.com">arthurcarvalhosantos@gmail.com</a>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/educacao.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>
  <h1>Educação</h1>
    <ul>
        <li>Graduação em <b>Engenharia Elétrica</b> pela <b>Universidade de Brasília</b><br>Início: Janeiro/2012<br>Previsão de Término: Dezembro/2017</li>
         <br>   
        <li>Intercâmbio Escolar na <b>University of California, San Diego</b><br>Duração: 12 meses<br>GPA: 3,725/4</li>
    </ul>
     <br>
  <br>
  <br>
  <br>
  <br>
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/experienciaprof.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>
  <h1>Experiência Profissional</h1>
  
  <ul>
    <li>Estágio profissional na <b>RCS Tecnologia</b>
      <br>Carga Horária: 20 horas
      <br>
    </li>
  <br>
  <br>
  <br>
  <br> 
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  </ul>  

</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/idiomas.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
</nav>

<article>
  <h1>Idiomas</h1>
  <ul>
    <li><b>Português:</b> Primeira Língua</li>
    <br>
    <li><b>Inglês:</b> Compreende bem, fala bem, lê bem, escreve bem</li>
    <br>
    <li><b>Francês:</b> Compreende pouco, fala pouco, lê razoavelmente, escreve pouco</li>
    <br>
    <li><b>Espanhol:</b> Compreende pouco, fala pouco, lê razoavelmente, escreve pouco</li>
</ul>
 <br>
  <br>
  <br>
  <br>
   <br>
    </article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/cv/informatica.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/dados_pessoais">Dados Pessoais</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>

  <h1>Conhecimentos de Informática</h1>
  
  <ul>
    <li><b>Pacote Office:</b> Conhecimento Intermediário</li>
    <br>
    <li><b>Programação em C:</b> Conhecimento Avançado</li>
    <br>
    <li><b>Programação em Java:</b> Conhecimento Básico</li>
    <br>
    <li><b>MatLab/Simulink:</b> Conhecimento Avançado</li>
</ul>
<br>
  <br>
  <br>
  <br>
  <br>  
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/home/ativcompl.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 1px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/inicial">Início</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>

  <h1>Atividades Complementares</h1>

  <ul>
    <li>Projeto de Iniciação Científica
      <br>Tema: RTK positioning technique via RDS
      <br>Orientador: Prof. Renato Alves Borges
      <br>Instituição: Universidade de Brasília
      <br>
    </li>
      
      <br>
    
    <li>Monitoria de Laboratório de Eletromagnetismo II
      <br>Professor: Plínio Ricardo Ganime Alves
      <br>Instituição: Universidade de Brasília
      <br>
    </li>  
      
      <br>

    <li>Monitoria de Física II
      <br>Professor: Demétrio Antonio da Silva Filho
      <br>Instituição: Universidade de Brasília
      <br>
    </li>
  </ul>

</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/home/certificados.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 1px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/inicial">Início</a></li><br>
    <li><a href="/educacao">Educação</a></li><br>
    <li><a href="/ativcompl">Atividades Complementares</a></li><br>
    <li><a href="/certificados">Bolsas e Certificados</a></li><br>
    <li><a href="/exp_prof">Experiência Profissional</a></li><br>
    <li><a href="/idiomas">Idiomas</a></li><br>
    <li><a href="/informatica">Conhecimentos de Informática</a></li>
  </ul>
</nav>

<article>
  <h1>Bolsas e Certificados</h1>

    <ul>
    <li>Participação na <b>I Escola Internacional de Energia Solar 2015</b>
      <br>UnB, 28 horas 
      <br>
    </li>
      
      <br>
    
    <li>Bolsa para graduação sanduíche através do programa <b>Ciências sem Fronteiras/CAPES</b>
      <br>Vigência: 2014
      <br>
    </li>  
      
      <br>

    <li>Mini-cursos <b>Princípios de conversão CA/CC e Componente Principais de Sistema CC</b>
      <br>ONS, 14 horas
      <br>
    </li>
  </ul>
  <br>
  <br>
  <br>
  <br>
  
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/home/inicial.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 2px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Arthur Carvalho dos Santos</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/">Início</a></li><br>
    <li><a href="/dados_pessoais">CV</a></li><br>
    <li><a href="/materias">Matérias</a></li><br>
  </ul>
</nav>

<article>
  <h1>Bem-vindo!</h1>
   


  <br>
  <br>
  <br>
  <br>
  <br>
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/materias/materias.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

button:hover{
    background-color: #ffffff; 
    width: 50px;
    height: 15px;
    border: none;
    color: black;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
    margin: 2px 2px;
}

button{
    background-color: #000000; 
    width: 50px;
    height: 15px;
    border: none;
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    margin-right: 170px;
    border-left: 1px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>Matérias</h1>
</header>
  
<nav>
  <ul>
    <li><a href="/">Início</a></li><br>
    <li><a href="/dados_pessoais">CV</a></li><br>
    <li><a href="/materias">Matérias</a></li><br>
  </ul>
</nav>

<article>

    Adicionar Matéria
    <%= form_tag materias_path do %>
      <%=text_field_tag 'nome',nil ,placeholder:'Nome da Matéria'%>
      <%=text_field_tag 'creditos',nil, placeholder:'Créditos'%>
      <%=button_tag 'Adicionar', :class=>'button'%>

    <% end %>

    Remover Matéria 
    <%= form_tag remover_por_nome_materias_path, :method=> :delete do %>
      <%=text_field_tag 'nome',nil ,placeholder:'Nome da Matéria'%>
      <%=button_tag 'Remover'%>

    <% end %>
  
    <div>
      <table border="0" width="790" ">
        <tr>
          <th>Nome</th>
          <th>Créditos</th>
        </tr>




        <% Materia.all.each do |materia|%>
          <tr>
            <td align="center"><%=materia.nome %></td>
            <td align="center"><%=materia.creditos %></td>
            <td align="center"><%=link_to('Ver',materia_path(materia.id)) %></td>
          </tr>
        <% end %>
      </table>
    </div>  


 

  
</article>

<%= yield %>
<footer></footer>

</div>


</body>
</html>

app/views/materias/show.erb
<!DOCTYPE html>
<html>
<head>
<style>

button:hover{
    background-color: #ffffff; 
    width: 50px;
    height: 15px;
    border: none;
    color: black;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
    margin: 2px 2px;
}

button{
    background-color: #000000; 
    width: 50px;
    height: 15px;
    border: none;
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
}


header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}



article {
    border-left: 1px solid gray;
    border-right: 1px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1><%= @materia.nome %></h1>
</header>
  


<article>
  <h1>
    Provas     
  </h1>
  <%= form_tag materia_provas_path(@materia.id), :method=> :create do %>
      <%= date_field_tag 'data' %>
      <%= number_field_tag 'peso',nil ,placeholder:'Peso da Prova' %>
      <%= number_field_tag 'nota',nil ,placeholder:'Nota da Prova',step: '0.1' %>
      <%=button_tag 'Adicionar'%>

    <% end %>

    <div>
      <table border="0" width="790" ">
        <tr>
          <th>Data</th>
          <th>Prova</th>
          <th>Nota</th>
          <th>Peso</th>
          <% i = 0 %>
        </tr>

        <% @materia.provas.each do |prova|%>
          <tr>
          <% i = i+1 %>
            <td align="center"><%= prova.data %></td>
            <td align="center"><%="Prova #{i}"%></td>
            <td align="center"><%= prova.nota %></td>
            <td align="center"><%= prova.peso %></td>
          </tr>
        <% end %>
      </table>
    </div>

  <h1>
    Trabalhos     
  </h1>
  <%= form_tag materia_trabalhos_path(@materia.id), :method=> :create do %>
    <%= date_field_tag 'data' %>
    <%= text_field_tag 'nome',nil ,placeholder:'Nome do Trabalho' %>
    <%= number_field_tag 'peso',nil ,placeholder:'Peso do Trabalho' %>
    <%= number_field_tag 'nota',nil ,placeholder:'Nota do Trabalho' %>
    <%=button_tag 'Adicionar'%>

  <% end %>

<div>
      <table border="0" width="790" ">
        <tr>
          <th>Data</th>
          <th>Nome</th>
          <th>Nota</th>
          <th>Peso</th>
        </tr>

        <% @materia.trabalhos.each do |trabalho|%>
          <tr>
            <td align="center"><%= trabalho.data %></td>
            <td align="center"><%= trabalho.nome %></td>
            <td align="center"><%= trabalho.nota %></td>
            <td align="center"><%= trabalho.peso %></td>
          </tr>
        <% end %>
      </table>
    </div>



</article>

<%= yield %>

<footer>
  <%=link_to('Voltar',materias_path) %>
</footer>

</div>


</body>
</html>